apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    appstudio.openshift.io/application: my-app
    appstudio.openshift.io/component: label-operator-53op
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: label-operator-53op
  namespace: yherzog-tenant
spec:
  url: https://github.com/yftacherzog/label-operator
