apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: label-operator-53op
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: label-operator-53op
    app.kubernetes.io/part-of: my-app
  name: label-operator-53op
  namespace: yherzog-tenant
spec:
  port:
    targetPort: 8080
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: label-operator-53op
    weight: 100
status: {}
